datashield:
  whitelist:
    - dsBase
springdoc:
  swagger-ui:
    enabled: false

spring:
  security:
    user:
      name: admin
      roles:
        - SU

server:
  error:
    include-binding-errors: always
    include-message: always
---
spring:
  profiles: development
  security:
    user:
      password: admin
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'https://auth.molgenis.org'
        opaquetoken:
          client-id: 'b396233b-cdb2-449e-ac5c-a0d28b38f791'

minio:
  url: http://localhost
  port: 9000
  access-key: molgenis
  secret-key: molgenis

management:
  endpoints:
    web:
      exposure:
        include: '*'


logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread|%.8X{sessionID}] %-5level %logger{36} - %msg%n"
  level:
    org.molgenis: DEBUG
    org.molgenis.r.RConnectionFactoryImpl: INFO
    org:
      springframework:
        web:
          context: DEBUG
---
spring:
  profiles: (development | test)
datashield:
  options:
    nfilter:
      string: 80
      kNN: 3
      tab: 3
      stringShort: 20
      noise: 0.25
      levels: 0.33
      glm: 5
      subset: 3
    datashield:
      privacyLevel: 5
